'''
ANSI escape characters for font effects.
'''
from ansi_esc.font.effects._effects import (
    reset, default, normal,
    bold, increased_intensity,
    faint, dim, decreased_intensity,
    italic,
    underline, singly_underlined,
    blink, blink_slow,
    blink_rapid,
    reverse, inverse, negative, swap_fg_bg,
    hidden, invisible, conceal,
    strikethrough, crossout,
    primary_font,
    alt_font,
    alt_font_first,
    alt_font_second,
    alt_font_third,
    alt_font_fourth,
    alt_font_fifth,
    alt_font_sixth,
    alt_font_seventh,
    alt_font_eighth,
    alt_font_ninth,
    fraktur, gothic,
    double_underline,
    reset_intensity, bold_off, faint_off, dim_off,
    italic_off,
    underline_off,
    blink_off,
    reverse_off, inverse_off, positive, swap_fg_bg_off,
    hidden_off, invisible_off, reveal,
    strikethrough_off, crossout_off,
    framed,
    encircled,
    overlined,
    framed_and_encircled_off,
    overlined_off
)
